name: app-back

services:
    db:
       container_name: mean-db
       image: mongo
       ports:
         - 27017:27017
       volumes:
         - ./mongo:/data/db
       restart: always

volumes:
  mongo:
